"use client";
import { useEffect, useState } from "react";

const TABS = ["الكلمات المفتاحية", "مكتشف الفئات", "متتبع الكتب", "منسّق الوصف", "حاسبة الأرباح"];
const DOMAINS = ["amazon.com", "amazon.co.uk", "amazon.de", "amazon.fr", "amazon.it", "amazon.es", "amazon.ca"];

export default function Home() {
  const [tab, setTab] = useState(0);
    const [domain, setDomain] = useState("amazon.com");

      return (
          <div className="wrap">
                <header>
                        <h1>📚 AllWDbook</h1>
                                <span className="mut">أدوات ناشري أمازون KDP</span>
                                      </header>
                                            <select value={domain} onChange={e => setDomain(e.target.value)}>
                                                    {DOMAINS.map(d => <option key={d} value={d}>{d}</option>)}
                                                          </select>
                                                                <div className="tabs">
                                                                        {TABS.map((t, i) => (
                                                                                  <button key={t} className={"tab" + (i === tab ? " on" : "")} onClick={() => setTab(i)}>{t}</button>
                                                                                          ))}
                                                                                                </div>
                                                                                                      {tab === 0 && <Keywords domain={domain} />}
                                                                                                            {tab === 1 && <Categories domain={domain} />}
                                                                                                                  {tab === 2 && <Tracker domain={domain} />}
                                                                                                                        {tab === 3 && <Formatter />}
                                                                                                                              {tab === 4 && <Calc />}
                                                                                                                                  </div>
                                                                                                                                    );
                                                                                                                                    }

                                                                                                                                    function Keywords({ domain }) {
                                                                                                                                      const [q, setQ] = useState("");
                                                                                                                                        const [d, setD] = useState(null);
                                                                                                                                          const [busy, setBusy] = useState(false);

                                                                                                                                            async function run() {
                                                                                                                                                if (!q) return;
                                                                                                                                                    setBusy(true);
                                                                                                                                                        const r = await fetch(`/api/keywords?q=${encodeURIComponent(q)}&domain=${domain}`);
                                                                                                                                                            setD(await r.json());
                                                                                                                                                                setBusy(false);
                                                                                                                                                                  }

                                                                                                                                                                    return (
                                                                                                                                                                        <div className="card">
                                                                                                                                                                              <input placeholder="اكتب كلمة مفتاحية… مثال: gratitude journal" value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === "Enter" && run()} />
                                                                                                                                                                                    <button className="go" onClick={run}>{busy ? "جاري التحليل…" : "حلّل السوق"}</button>
                                                                                                                                                                                          {d && (
                                                                                                                                                                                                  <>
                                                                                                                                                                                                            {d.mock && <p className="mut">⚠️ بيانات تجريبية — أضف RAINFOREST_API_KEY لتفعيل البيانات الحقيقية.</p>}
                                                                                                                                                                                                                      <div className="grid" style={{ marginTop: 12 }}>
                                                                                                                                                                                                                                  <div className="kpi"><b>{d.metrics.score}/100</b><span>درجة الفرصة</span></div>
                                                                                                                                                                                                                                              <div className="kpi"><b>{d.metrics.avgBsr.toLocaleString()}</b><span>متوسط BSR</span></div>
                                                                                                                                                                                                                                                          <div className="kpi"><b>{d.metrics.avgDailySales}</b><span>مبيعات/يوم للكتاب</span></div>
                                                                                                                                                                                                                                                                      <div className="kpi"><b>${d.metrics.avgPrice}</b><span>متوسط السعر</span></div>
                                                                                                                                                                                                                                                                                  <div className="kpi"><b>${d.metrics.nicheMonthlyRoyalty.toLocaleString()}</b><span>عائد المجال شهرياً</span></div>
                                                                                                                                                                                                                                                                                              <div className="kpi"><b>{d.metrics.avgReviews}</b><span>متوسط المراجعات</span></div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                  <h3>كلمات مقترحة</h3>
                                                                                                                                                                                                                                                                                                                            <div>{d.suggestions.map(s => <span key={s} className="chip" onClick={() => setQ(s)}>{s}</span>)}</div>
                                                                                                                                                                                                                                                                                                                                      <h3>أفضل النتائج</h3>
                                                                                                                                                                                                                                                                                                                                                {d.books.map(b => (
                                                                                                                                                                                                                                                                                                                                                            <div key={b.asin} className="row">
                                                                                                                                                                                                                                                                                                                                                                          <span>{b.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                        <span className="mut">${b.price} · BSR {b.bsr.toLocaleString()} · ⭐{b.rating} ({b.reviews})</span>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                  function Categories({ domain }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const [rows, setRows] = useState([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                          fetch(`/api/categories?domain=${domain}`).then(r => r.json()).then(j => setRows(j.rows));
                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [domain]);

                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mut">الفئات مرتبة من الأسهل للأصعب — كلما ارتفع BSR المطلوب للوصول لأفضل 100، كانت الفئة أسهل.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {rows.map(c => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={c.id} className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{c.path}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="mut">{c.difficulty} · BSR ≤ {c.top100Bsr.toLocaleString()} · {c.salesToTop100}/يوم</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function Tracker({ domain }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const [asin, setAsin] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const [items, setItems] = useState([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setItems(JSON.parse(localStorage.getItem("awd_track") || "[]"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function save(v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setItems(v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem("awd_track", JSON.stringify(v));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async function add() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!asin) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const r = await fetch(`/api/books?asin=${asin}&domain=${domain}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const b = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        save([b, ...items.filter(x => x.asin !== b.asin)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setAsin("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async function refreshAll() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const out = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const it of items) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const r = await fetch(`/api/books?asin=${it.asin}&domain=${it.domain}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    out.push(await r.json());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            save(out);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input placeholder="ASIN الكتاب (مثال: B08XYZ1234)" value={asin} onChange={e => setAsin(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="go" onClick={add}>أضف للتتبع</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {items.length > 0 && <p className="mut" onClick={refreshAll}>🔄 اضغط هنا لتحديث كل الكتب</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {items.map(b => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={b.asin} className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{b.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="mut">BSR {b.bsr?.toLocaleString()} · {b.monthly?.units} نسخة/شهر · ${b.monthly?.royalty} عائد</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function Formatter() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [t, setT] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const html = t
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .split("\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .map(p => p.trim())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .filter(Boolean)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .map(p => p.startsWith("- ") ? "<ul>" + p.split("\n").map(l => `<li>${l.replace(/^- /, "")}</li>`).join("") + "</ul>" : p.startsWith("# ") ? `<h4>${p.slice(2)}</h4>` : `<p>${p}</p>`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .join("");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mut">اكتب الوصف: سطر يبدأ بـ # = عنوان، سطر يبدأ بـ - = نقطة قائمة.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea rows={8} value={t} onChange={e => setT(e.target.value)} placeholder={"# لماذا هذا الكتاب؟\n\n- 120 صفحة\n- تصميم أنيق"} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>المعاينة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="prev" dangerouslySetInnerHTML={{ __html: html }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>كود HTML لأمازون</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea rows={5} readOnly value={html} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mut">الأحرف: {t.length}/4000</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function Calc() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [p, setP] = useState(12.99);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [pg, setPg] = useState(120);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const [color, setColor] = useState(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const cost = color ? 0.85 + pg * 0.07 : 0.85 + pg * 0.012;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const roy = Math.max(0, p * 0.6 - cost);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="mut">سعر البيع</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="number" value={p} onChange={e => setP(+e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="mut">عدد الصفحات</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="number" value={pg} onChange={e => setPg(+e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="mut"><input type="checkbox" checked={color} onChange={e => setColor(e.target.checked)} style={{ width: "auto" }} /> طباعة ملونة</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="kpi"><b>${cost.toFixed(2)}</b><span>تكلفة الطباعة</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="kpi"><b>${roy.toFixed(2)}</b><span>عائدك لكل نسخة</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          